"""Autonomous PoC-development agent commands."""

from __future__ import annotations

import json
import shlex
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console

from route_hacker.poc_agent import (
    PocAgentRunConfig,
    PocVerifierRunConfig,
    run_poc_agent,
    run_poc_verifier,
)


poc_app = typer.Typer(
    help="Launch an autonomous Agent that writes, executes, and revises a PoC",
    no_args_is_help=True,
)
console = Console()


def main() -> None:
    """Expose the standalone PoC command group for module execution."""
    poc_app()


@poc_app.command("run")
def run(
    audit_report: Path = typer.Argument(
        ...,
        help="Audit report supplied to the PoC Agent",
        exists=True,
        dir_okay=False,
        readable=True,
    ),
    output_dir: Path = typer.Option(
        ...,
        "--output-dir",
        "-o",
        help="Local directory for prompt, Agent event stream, and run metadata",
    ),
    poc_workspace: str = typer.Option(
        ...,
        "--poc-workspace",
        help="Artifact workspace visible to the Agent; may be local or remote",
    ),
    agent_cwd: Path = typer.Option(
        Path.cwd(),
        "--agent-cwd",
        help="Local TraeX working root",
        exists=True,
        file_okay=False,
    ),
    traex: str = typer.Option(
        "traex",
        "--traex",
        help="TraeX command, optionally including fixed wrapper arguments",
    ),
    model: Optional[str] = typer.Option(None, "--model", help="Optional TraeX model override"),
    token_limit: int = typer.Option(
        800_000,
        "--token-limit",
        min=1,
        help="Maximum observed aggregate input and output tokens for the PoC Agent",
    ),
    timeout: int = typer.Option(
        7_200,
        "--timeout",
        min=1,
        help="Wall-clock timeout in seconds",
    ),
    confirmation_request: Optional[Path] = typer.Option(
        None,
        "--confirmation-request",
        help="Immutable finding request generated by the stage-2 confirmation bridge",
    ),
) -> None:
    """Run one independent Agent session until PoC completion or a resource limit."""
    command = shlex.split(traex)
    if not command:
        raise typer.BadParameter("--traex must contain an executable")
    result = run_poc_agent(
        PocAgentRunConfig(
            audit_report=audit_report,
            output_dir=output_dir,
            poc_workspace=poc_workspace,
            agent_cwd=agent_cwd,
            traex_command=command,
            model=model,
            token_limit=token_limit,
            timeout_seconds=timeout,
            confirmation_request=confirmation_request,
        )
    )
    console.print(json.dumps(result.to_dict(), indent=2, ensure_ascii=False))
    if not result.succeeded:
        raise typer.Exit(1)


@poc_app.command("verify")
def verify(
    audit_report: Path = typer.Argument(
        ...,
        help="Original audit report supplied to the verifier",
        exists=True,
        dir_okay=False,
        readable=True,
    ),
    poc_artifact: str = typer.Option(
        ...,
        "--poc-artifact",
        help="Path or URI of the final PoC artifact to verify",
    ),
    reproduce_command: str = typer.Option(
        ...,
        "--reproduce-command",
        help="Command the verifier should use as the primary reproduction entrypoint",
    ),
    verifier_workspace: str = typer.Option(
        ...,
        "--verifier-workspace",
        help="Workspace where verifier receipts and logs should be written",
    ),
    output_dir: Path = typer.Option(
        ...,
        "--output-dir",
        "-o",
        help="Local directory for verifier prompt, event stream, and run metadata",
    ),
    agent_cwd: Path = typer.Option(
        Path.cwd(),
        "--agent-cwd",
        help="Local TraeX working root",
        exists=True,
        file_okay=False,
    ),
    traex: str = typer.Option(
        "traex",
        "--traex",
        help="TraeX command, optionally including fixed wrapper arguments",
    ),
    model: Optional[str] = typer.Option(None, "--model", help="Optional TraeX model override"),
    timeout: int = typer.Option(
        3_600,
        "--timeout",
        min=1,
        help="Wall-clock timeout in seconds",
    ),
    confirmation_request: Optional[Path] = typer.Option(
        None,
        "--confirmation-request",
        help="Immutable finding request generated by the stage-2 confirmation bridge",
    ),
    developer_receipt: Optional[Path] = typer.Option(
        None,
        "--developer-receipt",
        help="Developer receipt which the independent verifier must bind by SHA-256",
    ),
) -> None:
    """Run one independent verifier Agent session against a completed PoC."""
    command = shlex.split(traex)
    if not command:
        raise typer.BadParameter("--traex must contain an executable")
    result = run_poc_verifier(
        PocVerifierRunConfig(
            audit_report=audit_report,
            output_dir=output_dir,
            poc_artifact=poc_artifact,
            reproduce_command=reproduce_command,
            verifier_workspace=verifier_workspace,
            agent_cwd=agent_cwd,
            traex_command=command,
            model=model,
            timeout_seconds=timeout,
            confirmation_request=confirmation_request,
            developer_receipt=developer_receipt,
        )
    )
    console.print(json.dumps(result.to_dict(), indent=2, ensure_ascii=False))
    if not result.succeeded:
        raise typer.Exit(1)


if __name__ == "__main__":
    main()
